spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/webnotes?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: 233233
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      auto-commit: true
      pool-name: webnotes
      minimum-idle: 10
      maximum-pool-size: 30
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
  data:
    redis:
      host: 72.18.82.111
      port: 6379
      password: shirakawatyu

minio:
  endpoint: http://72.18.82.111:9000
  bucketName: webnotes
  accessKey: oE7nJPCLXjpaTPef
  secretKey: FfpRs0qSBHI3DzMQgidOFrR3NVkb5QWg

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: org.shirakawatyu.webnotes.pojo

server:
  port: 8083
note:
  image:
    url: https://res.shirakawatyu.top/
  cors:
    url: http://127.0.0.1:3000

