spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/webnotes?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: 233233
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      auto-commit: true
      pool-name: webnotes
      minimum-idle: 10
      maximum-pool-size: 30
  mail:
    protocol: smtps
    port: 465
    host: smtp.163.com
    username: shirakawatyu@163.com
    password: DDAAVFPIPAMYKNHP
  data:
    redis:
      host: 72.18.82.111
      port: 6379
      password: shirakawatyu

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: org.shirakawatyu.webnotes.pojo

server:
  port: 8081

note:
  cors:
    url: http://127.0.0.1:3000

